# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6555fe0a95e7a0c0172f35e5f3e63986e8bd67211fef1177d1d9b09ae3a2bd24654552721103a5e8d8eb246321a7af4025454d1a879449021921dc8110e01a93

test:
  secret_key_base: fda0c12782612ebaa204904f6bcbd01d0dbe23359b1edb3fe1a31fb1b9f871504c3edf1ddb247dec7daf7469f4b3e5280237ad84797f885acd7d32834745a55e

staging:
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
